FROM nginx:stable-alpine

COPY conf/nginx.dev.conf /etc/nginx/conf.d/default.conf

# RUN apk add --no-cache nano iputils

RUN mkdir -p /tmp \
    && chmod 777 /tmp

EXPOSE 8080 8443

CMD ["nginx", "-g", "daemon off;"]
